import { 
  Search, 
  MessageSquare, 
  Image, 
  Music, 
  FileText, 
  Microscope, 
  Zap, 
  Layout, 
  Box as Cube, 
  Mic2, 
  GraduationCap, 
  Folder,
  Star, 
  Bot, 
  Shield, 
  Heart, 
  LineChart, 
  Home, 
  Gamepad, 
  Beaker,
  Scale, 
  Languages, 
  Car, 
  Leaf, 
  Shirt, 
  Building2,
  Users, 
  Brain, 
  Code, 
  Video, 
  Camera, 
  Briefcase,
  Database,
  Headphones,
  Radio,
  Palette,
  Building,
  Factory,
  Truck,
  Film,
  Mountain,
  Waves,
  Pencil,
  Dumbbell,
  Eye,
  ArrowUpRight,
  Rocket,
  FlaskConical,
  CircuitBoard,
  Globe,
  Glasses,
  Plane,
  Printer,
  Cloud,
  CheckSquare,
  Clock,
  ShoppingCart,
  Server,
  PenTool
} from 'lucide-react';
import { AiBrain } from '../components/icons/AiBrain';
import { Acoustic } from '../components/icons/Acoustic';

export const iconMap = {
  // Base icons
  MessageSquare,
  Image,
  Music,
  FileText,
  Microscope,
  Zap,
  Layout,
  Cube,
  Mic2,
  GraduationCap,
  Bot,
  Shield,
  Heart,
  LineChart,
  Home,
  Gamepad,
  Beaker,
  Scale,
  Languages,
  Car,
  Leaf,
  Shirt,
  Building2,
  Users,
  Brain,
  Code,
  Video,
  Camera,
  Briefcase,
  Database,
  Headphones,
  Radio,
  Palette,
  Building,
  Factory,
  Truck,
  Film,
  Mountain,
  Waves,
  Pencil,
  Dumbbell,
  Eye,
  Rocket,
  FlaskConical,
  CircuitBoard,
  Globe,
  Glasses,
  Folder,
  Search,
  Star,
  ArrowUpRight,
  Plane,
  Printer,
  Cloud,
  CheckSquare,
  Clock,
  ShoppingCart,
  Server,
  PenTool,

  // Custom icons
  AiBrain,
  Acoustic,

  // Category mappings
  acoustic: Acoustic,
  agroalimentaire: Factory,
  assistants: Bot,
  automatisation: Zap,
  blockchain: CircuitBoard,
  ecommerce: ShoppingCart,
  finance: LineChart,
  gestion: CheckSquare,
  impression: Printer,
  iot: Cloud,
  logistique: Truck,
  meteo: Cloud,
  mlops: Server,
  mode: Shirt,
  musees: Building,
  productivite: Clock,
  redaction: PenTool,
  simulation: Globe,
  visualisation: Eye,
  aviation: Plane,
  
  // Ajout des mappings pour les noms d'icônes
  Speaker: Acoustic,  // Pour la catégorie acoustique

  // Additional mappings
  education: GraduationCap,
  sante: Heart,
  gaming: Gamepad,
  musique: Music,
  video: Video,
  photo: Camera,
  design: Palette,
  communication: MessageSquare,
  securite: Shield,
  developpement: Code,
  data: Database,
  audio: Headphones,
  media: Film,
  sport: Dumbbell,
  traduction: Languages,
  transport: Car,
  environnement: Leaf,
  science: Microscope,
  recherche: Search,
  innovation: Rocket,
  industrie: Factory,
  immobilier: Building2,
  technologie: CircuitBoard,
  cloud: Cloud,
  intelligence: Brain,
  robotique: Bot,
  realitevirtuelle: Glasses,
  optimisation: LineChart,
  autre: Folder
} as const;
