-- Mettre à jour toutes les icônes manquantes
BEGIN;

UPDATE categories SET icon = CASE name
    -- Catégories avec icônes déjà fonctionnelles
    WHEN '3D & Animation' THEN 'Cube'
    WHEN 'Agriculture & Environnement' THEN 'Leaf'
    WHEN 'Analyse de données' THEN 'LineChart'
    WHEN 'Architecture & Construction' THEN 'Building2'
    WHEN 'Art & Créativité' THEN 'Palette'
    WHEN 'Astronomie & Espace' THEN 'Rocket'
    WHEN 'Audio & Musique' THEN 'Music'
    WHEN 'Audio & Voix' THEN 'Headphones'
    WHEN 'Automobile' THEN 'Car'
    WHEN 'Biotechnologie' THEN 'Flask'
    WHEN 'Business & Marketing' THEN 'Briefcase'
    WHEN 'Chimie & Matériaux' THEN 'FlaskConical'
    WHEN 'Cybersécurité' THEN 'Shield'
    WHEN 'Design' THEN 'Pencil'
    WHEN 'Développement' THEN 'Code'
    WHEN 'Éducation' THEN 'GraduationCap'
    WHEN 'Énergie' THEN 'Zap'
    WHEN 'Gaming' THEN 'Gamepad'
    WHEN 'Génération d''images' THEN 'Image'
    WHEN 'Géologie' THEN 'Mountain'
    WHEN 'Immobilier' THEN 'Home'
    WHEN 'Industrie' THEN 'Factory'
    WHEN 'Intelligence Artificielle Générale' THEN 'Brain'
    WHEN 'IoT & Robotique' THEN 'CircuitBoard'
    WHEN 'Médias & Divertissement' THEN 'Film'
    WHEN 'Métavers & Mondes virtuels' THEN 'Globe'
    WHEN 'Mode & Style' THEN 'Shirt'
    WHEN 'Océanographie' THEN 'Waves'
    WHEN 'Photographie' THEN 'Camera'
    WHEN 'Réalité augmentée & virtuelle' THEN 'Glasses'
    WHEN 'Recherche' THEN 'Search'
    WHEN 'Recherche scientifique' THEN 'Microscope'
    WHEN 'Ressources humaines' THEN 'Users'
    WHEN 'Robotique' THEN 'Bot'
    WHEN 'Santé' THEN 'Heart'
    WHEN 'Science des données' THEN 'Database'
    WHEN 'Sport & Fitness' THEN 'Dumbbell'
    WHEN 'Télécommunications' THEN 'Radio'
    WHEN 'Traduction' THEN 'Languages'
    WHEN 'Traitement du Langage Naturel' THEN 'MessageSquare'
    WHEN 'Transport' THEN 'Truck'
    WHEN 'Vidéo' THEN 'Video'
    WHEN 'Voix & Parole' THEN 'Mic2'

    -- Nouvelles correspondances pour les icônes "Folder"
    WHEN 'Acoustique' THEN 'Speaker'
    WHEN 'Agents & Automatisation' THEN 'Bot'
    WHEN 'Agriculture' THEN 'Leaf'
    WHEN 'Agroalimentaire' THEN 'Coffee'
    WHEN 'Archéologie' THEN 'Mountain'
    WHEN 'Assistants & Chatbots' THEN 'MessageCircle'
    WHEN 'Automatisation' THEN 'Cog'
    WHEN 'Automobile & Transport' THEN 'Car'
    WHEN 'Aviation' THEN 'Plane'
    WHEN 'Blockchain & Web3' THEN 'Link'
    WHEN 'Collaboration IA' THEN 'Users'
    WHEN 'Construction' THEN 'Building2'
    WHEN 'Création musicale' THEN 'Music'
    WHEN 'Développement d''Agents' THEN 'Bot'
    WHEN 'Données & Préparation' THEN 'Database'
    WHEN 'E-commerce' THEN 'ShoppingCart'
    WHEN 'Énergie & Climat' THEN 'Zap'
    WHEN 'Environnement' THEN 'Leaf'
    WHEN 'Finance' THEN 'DollarSign'
    WHEN 'Frameworks & Bibliothèques' THEN 'Code'
    WHEN 'Génération de Code' THEN 'Code'
    WHEN 'Gestion des Tâches' THEN 'ListCheck'
    WHEN 'Impression 3D' THEN 'Printer'
    WHEN 'Industrie 4.0' THEN 'Factory'
    WHEN 'IoT & Domotique' THEN 'Cpu'
    WHEN 'Jeux vidéo' THEN 'Gamepad'
    WHEN 'Juridique' THEN 'FileText'
    WHEN 'Logistique' THEN 'Box'
    WHEN 'Météo' THEN 'Cloud'
    WHEN 'MLOps & Déploiement' THEN 'Server'
    WHEN 'Mode & Design' THEN 'Scissors'
    WHEN 'Musées & Patrimoine' THEN 'Landmark'
    WHEN 'Nanotechnologie' THEN 'Microscope'
    WHEN 'Optimisation & Performance' THEN 'LineChart'
    WHEN 'Outils de Données' THEN 'Database'
    WHEN 'Productivité' THEN 'Clock'
    WHEN 'Psychologie' THEN 'Brain'
    WHEN 'Réalité Mixte' THEN 'Glasses'
    WHEN 'Recommandation' THEN 'Star'
    WHEN 'Rédaction & Contenu' THEN 'PenTool'
    WHEN 'RH & Recrutement' THEN 'Users'
    WHEN 'Science & Recherche' THEN 'Microscope'
    WHEN 'Simulation' THEN 'Settings'
    WHEN 'Traduction & Localisation' THEN 'Languages'
    WHEN 'Vidéo & Animation' THEN 'Video'
    WHEN 'Vision par Ordinateur' THEN 'Eye'
    WHEN 'Visualisation & Analyse' THEN 'PieChart'
    ELSE 'Folder' -- Icône par défaut
END;

-- Vérifier les mises à jour
SELECT name, icon
FROM categories
WHERE icon = 'Folder'
ORDER BY name;

COMMIT;
