-- Corriger les noms d'icônes pour correspondre exactement à Lucide Icons
BEGIN;

UPDATE categories SET icon = CASE name
    -- Corrections des icônes existantes
    WHEN 'Agroalimentaire' THEN 'coffee'
    WHEN 'Analyse de données' THEN 'bar-chart'
    WHEN 'Archéologie' THEN 'hammer'
    WHEN 'Assistants & Chatbots' THEN 'message-circle'
    WHEN 'Audio & Voix' THEN 'speaker'
    WHEN 'Automatisation' THEN 'cog'
    WHEN 'Aviation' THEN 'plane'
    WHEN 'Blockchain & Web3' THEN 'link'
    WHEN 'Construction' THEN 'tool'
    WHEN 'Design' THEN 'pen'
    WHEN 'E-commerce' THEN 'shopping-cart'
    WHEN 'Énergie & Climat' THEN 'sun'
    WHEN 'Finance' THEN 'dollar-sign'
    WHEN 'Frameworks & Bibliothèques' THEN 'library'
    WHEN 'Gaming' THEN 'gamepad-2'
    WHEN 'Génération de Code' THEN 'code-2'
    WHEN 'Gestion des Tâches' THEN 'list-checks'
    WHEN 'Impression 3D' THEN 'printer'
    WHEN 'IoT & Domotique' THEN 'cpu'
    WHEN 'IoT & Robotique' THEN 'cpu'
    WHEN 'Juridique' THEN 'file-text'
    WHEN 'Logistique' THEN 'box'
    WHEN 'Météo' THEN 'cloud'
    WHEN 'MLOps & Déploiement' THEN 'server'
    WHEN 'Mode & Design' THEN 'scissors'
    WHEN 'Mode & Style' THEN 'scissors'
    WHEN 'Musées & Patrimoine' THEN 'landmark'
    WHEN 'Outils de Données' THEN 'tool'
    WHEN 'Productivité' THEN 'clock'
    WHEN 'Recommandation' THEN 'star'
    WHEN 'Rédaction & Contenu' THEN 'pen-tool'
    WHEN 'Simulation' THEN 'settings'
    WHEN 'Télécommunications' THEN 'phone'
    WHEN 'Vision par Ordinateur' THEN 'eye'
    WHEN 'Visualisation & Analyse' THEN 'pie-chart'
    WHEN 'Voix & Parole' THEN 'speaker'
    
    -- Autres catégories (en minuscules)
    WHEN '3D & Animation' THEN 'cube'
    WHEN 'Acoustique' THEN 'music'
    WHEN 'Agents & Automatisation' THEN 'bot'
    WHEN 'Agriculture' THEN 'leaf'
    WHEN 'Agriculture & Environnement' THEN 'leaf'
    WHEN 'Architecture & Construction' THEN 'building-2'
    WHEN 'Art & Créativité' THEN 'palette'
    WHEN 'Astronomie & Espace' THEN 'rocket'
    WHEN 'Audio & Musique' THEN 'music'
    WHEN 'Automobile' THEN 'car'
    WHEN 'Automobile & Transport' THEN 'car'
    WHEN 'Biotechnologie' THEN 'flask'
    WHEN 'Business & Marketing' THEN 'briefcase'
    WHEN 'Chimie & Matériaux' THEN 'flask'
    WHEN 'Collaboration IA' THEN 'users'
    WHEN 'Création musicale' THEN 'music'
    WHEN 'Cybersécurité' THEN 'shield'
    WHEN 'Développement' THEN 'code'
    WHEN 'Développement d''Agents' THEN 'bot'
    WHEN 'Données & Préparation' THEN 'database'
    WHEN 'Éducation' THEN 'graduation-cap'
    WHEN 'Énergie' THEN 'zap'
    WHEN 'Environnement' THEN 'leaf'
    WHEN 'Génération d''images' THEN 'image'
    WHEN 'Géologie' THEN 'mountain'
    WHEN 'Immobilier' THEN 'home'
    WHEN 'Industrie' THEN 'factory'
    WHEN 'Industrie 4.0' THEN 'factory'
    WHEN 'Intelligence Artificielle Générale' THEN 'brain'
    WHEN 'Jeux vidéo' THEN 'gamepad'
    WHEN 'Métavers & Mondes virtuels' THEN 'globe'
    WHEN 'Nanotechnologie' THEN 'microscope'
    WHEN 'Océanographie' THEN 'waves'
    WHEN 'Optimisation & Performance' THEN 'line-chart'
    WHEN 'Photographie' THEN 'camera'
    WHEN 'Psychologie' THEN 'brain'
    WHEN 'Réalité augmentée & virtuelle' THEN 'glasses'
    WHEN 'Réalité Mixte' THEN 'glasses'
    WHEN 'Recherche' THEN 'search'
    WHEN 'Recherche scientifique' THEN 'flask-conical'
    WHEN 'Ressources humaines' THEN 'users'
    WHEN 'RH & Recrutement' THEN 'users'
    WHEN 'Robotique' THEN 'bot'
    WHEN 'Santé' THEN 'heart'
    WHEN 'Science des données' THEN 'database'
    WHEN 'Science & Recherche' THEN 'flask-conical'
    WHEN 'Sport & Fitness' THEN 'dumbbell'
    WHEN 'Traduction' THEN 'languages'
    WHEN 'Traduction & Localisation' THEN 'languages'
    WHEN 'Traitement du Langage Naturel' THEN 'message-square'
    WHEN 'Transport' THEN 'truck'
    WHEN 'Vidéo' THEN 'video'
    WHEN 'Vidéo & Animation' THEN 'video'
    ELSE 'circle' -- Icône par défaut
END;

-- Vérifier les mises à jour
SELECT name, icon
FROM categories
WHERE icon = 'circle'
ORDER BY name;

COMMIT;
